var actionsConstants = {
  ADD_FIRST_TILE: "ADD_FIRST_TILE",
  ADD_TILE_DOWN: "ADD_TILE_DOWN",
  ADD_TILE_UP: "ADD_TILE_UP",
  LOAD_TILE_DATA: "LOAD_TILE_DATA",
  LOAD_FIRST_TILE_DATA: "LOAD_FIRST_TILE_DATA",
  GO_TO_ROUTE: "GO_TO_ROUTE",
  GO_TO_EXISTING_ROUTE: "GO_TO_EXISTING_ROUTE",
  UPDATE_SOMETHING: "UPDATE_SOMETHING"
};

module.exports = actionsConstants;